version: "3.7"

services:
    # image project
    app:
        container_name: maker
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        container_name: maker-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "3097:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        container_name: maker-db
        image: mariadb:10.4
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3389:3306"
        networks:
            - laravel

    # redis
    redis:
        container_name: maker-redis
        image: redis:latest
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
